version: '3'
services:
  mariadb:
    image: mariadb
    container_name: mariadba6
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: agente
      MARIADB_USER_PASSWORD: 0traClave
      MARIADB_DATABASE: PEPS
    volumes:
      - mariadb_dataa6:/var/lib/mysql
      - ./Juegos.sql://docker-entrypoint-initdb.d/Juegos.sql

    user: mysql
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmina6
    restart: always
    environment:
      - PMA_HOST=mariadb
    ports:
      - 7006:80
    depends_on:
      - mariadb
  python:
    build: .
    container_name: pythona6
    environment:
      DB_USERNAME: root
      DB_PASSWORD: example
      DB_DATABASE: PEPS
      DB_HOST: mariadb
      DB_PORT: 3306
      PORT: 8000
      HOST: 0.0.0.0
      SECRET_KEY: 'you-will-never-guess'
      DEBUG: "false"
    depends_on:
        - mariadb
  apache:
    build: ./apache
    ports:
      - 6006:80
      
volumes:
  mariadb_dataa6: